### YamlMime:Role 
title: Administrator 
metadata: 
  title: Administrator 
  description: Les administrateurs mettent en œuvre, suivent et maintiennent les solutions Microsoft, y compris les principaux services liés au calcul, au stockage, au réseau et à la sécurité.
uid: role.administrator 
summary: | 
  Les administrateurs mettent en œuvre, suivent et maintiennent les solutions Microsoft, y compris les principaux services liés au calcul, au stockage, au réseau et à la sécurité.
subTitle: Les administrateurs mettent en œuvre, surveillent et maintiennent les solutions Microsoft.
certificationPaths: 
- title: Azure Administrator
  linkedInKeywords: Azure Administrator
  uid: certification-path.azure-administrator 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-administrator
    levels:
    - intermediate
  - uid: certification.devops-engineer
    levels:
    - advanced      
- title: 'Microsoft 365 Certified: Messaging Administrator Associate'
  linkedInKeywords: 'Microsoft 365 Certified: Messaging Administrator Associate'
  uid: certification.m365-messaging-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-messaging-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: 'Microsoft 365 Certified: Modern Desktop Administrator Associate'
  linkedInKeywords: 'Microsoft 365 Certified: Modern Desktop Administrator Associate'
  uid: certification.modern-desktop
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.modern-desktop
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: 'Microsoft 365 Certified: Security Administrator Associate'
  linkedInKeywords: 'Microsoft 365 Certified: Security Administrator Associate'
  uid: certification.m365-security-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-security-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: 'Microsoft 365 Certified: Teamwork Administrator Associate'
  linkedInKeywords: 'Microsoft 365 Certified: Teamwork Administrator Associate'
  uid: certification.m365-teamwork-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-teamwork-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Microsoft Teams Administrator
  linkedInKeywords: Microsoft Teams Administrator
  uid: certification.m365-teams-administrator-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-teams-administrator-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-administrator
  requiredExams:
  - uid: exam.az-104
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
- uid: certification.m365-messaging-administrator
  requiredExams:
  - uid: exam.ms-203
- uid: certification.modern-desktop
  requiredExams:
  - uid: exam.md-100
  - uid: exam.md-101
- uid: certification.m365-security-administrator
  requiredExams:
  - uid: exam.ms-500
- uid: certification.m365-enterprise-administrator
  requiredExams:
  - uid: exam.ms-100
  - uid: exam.ms-101
- uid: certification.m365-teams-administrator-associate
  requiredExams:
  - uid: exam.ms-700
resources:
- title: Guide de formation et de certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Affiche de formation et de certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Aide à la certification
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de Microsoft Certification. Un modérateur du forum répondra sous 24 heures (du lundi au vendredi).
