### YamlMime:Role 
title: Développeur 
metadata: 
  title: Développeur 
  description: Les développeurs conçoivent, construisent, testent et maintiennent des solutions. Les développeurs mettent en œuvre des applications et des services en s'associant à des architecte en solutions et des clients.
uid: role.developer 
summary: | 
  Les développeurs conçoivent, construisent, testent et maintiennent des solutions. Les développeurs mettent en œuvre des applications et des services en s'associant à des architecte en solutions et des clients. 
subTitle: Les développeurs conçoivent, construisent, testent et maintiennent des solutions de cloud.
certificationPaths: 
- title: Azure Developer
  linkedInKeywords: Azure Developer
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Développeur d'applications pour Dynamics 365 pour les finances et les opérations
  linkedInKeywords: Développeur d'applications pour Dynamics 365 pour les finances et les opérations
  uid: certification.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Développeur Microsoft 365
  linkedInKeywords: Développeur Microsoft 365
  uid: certification.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
- title: Développeur Power Apps + Dynamics 365
  linkedInKeywords: Développeur Power Apps + Dynamics 365
  uid: certification.power-apps-and-d365-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-apps-and-d365-developer-associate
    levels:
    - intermediate 
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-203
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-apps-and-d365-developer-associate
  requiredExams:
  - uid: exam.pl-900
resources:
- title: Guide de formation et de certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Affiche de formation et de certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Support pour les certifications
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de certification Microsoft. Un modérateur du forum va répondre dans un jour ouvrable, du lundi au vendredi.
