### YamlMime:Role 
title: Ingénieur DevOps 
metadata: 
  title: Ingénieur DevOps 
  description: Les ingénieurs DevOps comprennent des personnes, des processus et des technologies pour délivrer de façon continue des produits et services de valeur, à la hauteur des besoins et objectifs professionnels des utilisateurs finaux.
uid: role.devops-engineer 
summary: | 
  Les ingénieurs DevOps comprennent des personnes, des processus et des technologies pour délivrer de façon continue des produits et services de valeur, à la hauteur des besoins et objectifs professionnels des utilisateurs finaux.
subTitle: Les ingénieurs DevOps comprennent des personnes, des processus et des technologies pour délivrer de façon continue des produits et services de valeur, à la hauteur des besoins et objectifs professionnels des utilisateurs finaux.
certificationPaths: 
- title: Ingénieur Azure DevOps
  linkedInKeywords: Ingénieur Azure DevOps
  uid: certification-path.devops 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-devops
    levels:
    - advanced    
certifications:
- uid: certification.azure-devops
  requiredExams:
  - uid: exam.az-400
resources:
- title: Guide de formation et de certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Affiche de formation et de certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Support pour les certifications
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de certification Microsoft. Un modérateur du forum va répondre dans un jour ouvrable, du lundi au vendredi.
