### YamlMime:Role 
title: Ingénieur en sécurité 
metadata: 
  title: Ingénieur en sécurité  
  description: Les ingénieurs en sécurité mettent en œuvre des contrôles de sécurité et une protection contre les menaces, gèrent l’identité et l’accès et protègent les données, les applications et les réseaux.  
uid: role.security-engineer 
summary: | 
  Les ingénieurs en sécurité mettent en œuvre des contrôles de sécurité et une protection contre les menaces, gèrent l’identité et l’accès et protègent les données, les applications et les réseaux.
subTitle: Les ingénieurs en sécurité mettent en œuvre des contrôles de sécurité et une protection contre les menaces, gèrent l’identité et l’accès et protègent les données, les applications et les réseaux.
certificationPaths: 
- title: Ingénieur en sécurité Azure
  linkedInKeywords: Ingénieur en sécurité Azure
  uid: certification-path.azure-security-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-security-engineer
    levels:
    - intermediate
   
certifications:
- uid: certification.azure-security-engineer
  requiredExams:
  - uid: exam.az-500
resources:
- title: Guide de formation et de certification Microsoft
  description: Découvrez toutes les certifications dans un guide de formation et de certification concis.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Affiche de formation et de certification
  description: Choisissez la voie de la réussite avec cette affiche de formation et de certification.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Support pour les certifications
  href: ../help.md
  description: Obtenez de l’aide à travers nos Forums de support de certification Microsoft. Un modérateur du forum va répondre dans un jour ouvrable, du lundi au vendredi.
